name: portfolio-admin ci/cd pipeline

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setting up the things
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Installing dependencies
        run: npm install

      - name: Building the source code
        run: npm run build

      - name: Quality gate analysis
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_SECRET }}
          SONAR_HOST_URL: ${{ vars.SONARQUBE_HOST }}
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.host.url=${SONAR_HOST_URL}
            -Dsonar.token=${SONARQUBE_TOKEN}
            -Dsonar.qualitygate.wait=true

      - name: Preparing the image
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master'||github.ref == 'refs/heads/release')
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
          VITE_APP_ENV: ${{ secrets.VITE_APP_ENV }}
          VITE_API_TIMEOUT: ${{ secrets.VITE_API_TIMEOUT }}
          VITE_PORTFOLIO_URL: ${{ secrets.VITE_PORTFOLIO_URL }}
          VITE_FRONTEND_URL: ${{ secrets.VITE_FRONTEND_URL }}
          VITE_FTP_URL: ${{ secrets.VITE_FTP_URL }}
          VITE_FTP_API_BASE_URL: ${{ secrets.VITE_FTP_API_BASE_URL }}
          VITE_PBADMIN_URL: ${{ secrets.VITE_PBADMIN_URL }}
          VITE_CAPTCHA_TIMEOUT: ${{ secrets.VITE_CAPTCHA_TIMEOUT }}
          VITE_APP_VERSION: ${{secrets.VITE_APP_VERSION}}
        run: |
          docker build --build-arg VITE_API_BASE_URL=${VITE_API_BASE_URL} --build-arg VITE_APP_ENV=${VITE_APP_ENV} --build-arg VITE_API_TIMEOUT=${VITE_API_TIMEOUT} --build-arg VITE_PORTFOLIO_URL=${VITE_PORTFOLIO_URL}  --build-arg VITE_FRONTEND_URL=${VITE_FRONTEND_URL} --build-arg VITE_FTP_URL=${VITE_FTP_URL} --build-arg VITE_FTP_API_BASE_URL=${VITE_FTP_API_BASE_URL} -t portfolio-admin-panel .
          docker tag portfolio-admin-panel ${DOCKER_USERNAME}/portfolio-admin-panel:latest

      - name: Publishing the image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_SECRET }}
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master'||github.ref == 'refs/heads/release')
        run: |
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker push ${DOCKER_USERNAME}/portfolio-admin-panel:latest

      - name: Deploying the code to development server
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          npm install -g caprover
          caprover deploy \
          --host ${{ secrets.CAPROVER_HOST }} \
          -p ${{ secrets.CAPROVER_PWD }} \
          --imageName ${{ secrets.DOCKER_USERNAME }}/portfolio-admin-panel:latest \
          --appName portfolio-dev-admin

      - name: Deploying the code to production server
        if: github.event_name == 'push' && github.ref == 'refs/heads/release'
        run: |
          npm install -g caprover
          caprover deploy \
          --host ${{ secrets.CAPROVER_PROD_HOST }} \
          -p ${{ secrets.CAPROVER_PROD_PWD }} \
          --imageName ${{ secrets.DOCKER_USERNAME }}/portfolio-admin-panel:latest \
          --appName portfolio
